name: Build SFI

on:
  workflow_dispatch:
  schedule:
    - cron: '10 15 * * *'

permissions:
  contents: write  # 重要：允许创建 release
  actions: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: set version
        run: |
          echo "SING_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | perl -ne 'if(/"tag_name":\s*"v([0-9a-zA-Z\.-]+)"/){ print "$1\n"; last }')" >> $GITHUB_ENV
          echo "SING_IOS_VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | perl -ne 'if(/"tag_name":\s*"v([0-9a-zA-Z\.-]+)"/){ print "$1\n"; last }')" >> $GITHUB_ENV
        shell: bash

      - name: set variables
        id: set_variables
        run: |
          echo "sing-box-v${{ env.SING_VERSION }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ env.SING_VERSION }}" == "${{ env.SING_IOS_VERSION }}" ]; then
            echo "SING_VERSION_MATCH=true" >> $GITHUB_ENV
          else
            echo "SING_VERSION_MATCH=false" >> $GITHUB_ENV
          fi

      - name: Checkout this repo
        if: ${{ env.SING_VERSION_MATCH != 'true' }}
        uses: actions/checkout@main

      - name: Setup Go
        if: ${{ env.SING_VERSION_MATCH != 'true' }}
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25

      - name: Setup Xcode stable
        if: ${{ env.SING_VERSION_MATCH != 'true' }}
        run: |-
          sudo xcode-select -s /Applications/Xcode.app


      - name: Install ldid (via brew)
        if: ${{ env.SING_VERSION_MATCH != 'true' }}
        run: |
          brew install ldid

      - name: Build TIPA
        if: ${{ env.SING_VERSION_MATCH != 'true' }}
        run: |
          cd $HOME

          git clone -b v${{ env.SING_VERSION }} --recurse-submodules --depth 1 https://github.com/SagerNet/sing-box.git
          cd $HOME/sing-box

          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          go run ./cmd/internal/build_libbox -target apple -platform ios
          mv Libbox.xcframework clients/apple

          export XCODEPROJ_NAME=sing-box
          export APPLICATION_NAME=sing-box
          export SCHEME_NAME=SFI

          cd clients/apple

          xcodebuild \
            -project $XCODEPROJ_NAME.xcodeproj \
            -scheme $SCHEME_NAME \
            -destination 'generic/platform=iOS' \
            -configuration Debug \
            -sdk iphoneos \
            build install \
            STRIP_INSTALLED_PRODUCT=NO \
            ARCHS=arm64 \
            CODE_SIGNING_ALLOWED=NO \
            ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO \
            ENABLE_BITCODE=NO \
            DSTROOT=packages/

          ldid -SSFI/SFI.entitlements packages/Applications/$APPLICATION_NAME.app/$APPLICATION_NAME
          ldid -SExtension/Extension.entitlements packages/Applications/$APPLICATION_NAME.app/PlugIns/Extension.appex/Extension
          ldid -SIntentsExtension/IntentsExtension.entitlements packages/Applications/$APPLICATION_NAME.app/Extensions/IntentsExtension.appex/IntentsExtension

          mkdir -p packages/Payload
          cp -rp packages/Applications/$APPLICATION_NAME.app packages/Payload
          cd packages
          zip -qr $APPLICATION_NAME.tipa Payload
          mv $APPLICATION_NAME.tipa ${GITHUB_WORKSPACE}/${APPLICATION_NAME}-${{ env.SING_VERSION }}.tipa
          cd ${GITHUB_WORKSPACE}
          echo -e "SHA256 Checksum: \n$(sha256sum ${APPLICATION_NAME}-${{ env.SING_VERSION }}.tipa)" >> $GITHUB_STEP_SUMMARY

      - name: Create Release and Upload TIPA
        if: ${{ env.SING_VERSION_MATCH != 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.SING_VERSION }}
          name: ${{ env.SING_VERSION }}
          files: sing-box-${{ env.SING_VERSION }}.tipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 3
